vim.api.nvim_set_hl(0, "CmpItemKindText", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindField", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindClass", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindProperty", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindUnit", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindValue", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindEnum", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindColor", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindFile", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindReference", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindFolder", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindConstant", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindStruct", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindEvent", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindOperator", { fg = '#ffffff', bg = '#50fa7b' })
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", { fg = '#ffffff', bg = '#50fa7b' })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { fg = '#ffffff', bg = '#50fa7b' })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = '#ffffff', bg = '#50fa7b' })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = '#ffffff', bg = '#50fa7b' })
--
vim.cmd [[hi! CmpItemKindText guibg=#cc2451]]
vim.api.nvim_command("redraw")
