text="#f8f8f2"
subtle="#ff79c6"
warning-text="#bd93f9"
text-special-one="#6272a4"
text-special-two="#8be9fd"
top-bar-background="#44475a"
top-bar-text="#f8f8f2"
status-bar-background="#44475a"
status-bar-text="#f8f8f2"
status-bar-view-text="#f8f8f2"
list-selected-background="#44475a"
list-selected-text="#ff79c6"
command-text="#f8f8f2"
list-selected-inactive-text="#f8f8f2"
list-selected-inactive-background="#44475a"
controls-text="#f8f8f2"
controls-highlight="#ffb86c"
autocomplete-background="#44474a"
autocomplete-text="#f8f8f2"
autocomplete-selected-background="#282a36"
autocomplete-selected-text="#ff79c6"
button-color-one="#44475a"
button-color-two="#8be9fd"
timeline-name-text="#ff79c6"
