#!/usr/bin/env sh

# global settings

# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off

# move mouse to focused window
yabai -m config mouse_follows_focus          on
# yabai -m config window_placement             second_child

# floating windows always stay on top
yabai -m config window_topmost               on

# don't automatically rebalance windows
yabai -m config auto_balance                 on

# swap windows if moved with mouse
yabai -m config mouse_action1                move

# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   15

# SIP Required
# prevent border from being under the active window
# enable borders
# yabai -m config window_border                on
# yabai -m config active_window_border_topmost on
# yabai -m config window_border_width          2.5
# yabai -m config active_window_border_color   0xffff79c6
# yabai -m config normal_window_border_color   0xfff8f8f2


#exceptions
yabai -m rule --add app="Music" sticky=on layer=above manage=off
# need to install this to work
# https://github.com/FelixKratz/JankyBorders
borders active_color=0xffff79c6 inactive_color=0xfff8f8f2 width=8.0 2>/dev/null 1>&2 &
